apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-sample
  labels:
    apps: stuadmissionwebhook
webhooks:
- name: stuadmissionwebhook.stuadmissionwebhook.domain
  admissionReviewVersions: ["v1"]
  sideEffects: None
  rules:
  - apiGroups: ["*"]
    apiVersions: ["*"]
    operations: ["*"]
    resources: ["*"]
  namespaceSelector:
    matchExpressions:
    - key: app
      operator: In
      values: ["stuadmissionwebhook"]
  clientConfig:
    service:
      name: admissionservice
      namespace: stuadmissionwebhook
      path: /validate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrVENDQWVHZ0F3SUJBZ0lKQU0yN0NvNWdHSUxpTUEwR0NTcUdTSWIzRFFFQkN3VUFNQkl4RURBT0JnTlYKQkFNTUIzZGxZbWh2YjJzd0lCY05Nakl3TlRBME1ESTFNakEwV2hnUE1qRXlNakEwTVRBd01qVXlNRFJhTUJJeApFREFPQmdOVkJBTU1CM2RsWW1odmIyc3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCCkFRRHVVWXFpSHZVMHJvSnVHcVNTYk4yY3BCR215UXEwZmcxY0cvcGJBdmI1QkZkL2x0VW5aTml4U0Y1OGpUT2MKbjZWV3Flc2JSaldBYUFGbzErRXlEYXBoREM1cVgzZWkwY0I4VFV5N3lvR0FPOTFWWWp5NGpIVThIcitZMFZKWgpMb0lqdWhCTW9na1ZFYlROcVJLdm52L09RTUFQL28rTGt2cytFbDZvdmdHbzhWbUE1Vk41OFc0YkJiaUZMSjZmCnV5bkxRaUhUYWpKa0RVb3dRSkpaN2VyYytLVkdBbmQxOUZiS1NjQ0x0QmpRMWxWc1NEQklkSmltcUxYaUxZRDUKUFVXMWdRRTF3b1NhM2NoUkpMUTZ1Ymxtd0RMeTI2N3NXRnpYMlhiZ2xXTEkrd3BscGZDdCtrQU1LK2t4SzIraApNVG5ubzhCUVJ3ZFdHelhHRmlKTXNzZS9BZ01CQUFHalVEQk9NQjBHQTFVZERnUVdCQlN1K2FlNTVIZmhQTmEyCi9vcG90UHlGNlk1YnpUQWZCZ05WSFNNRUdEQVdnQlN1K2FlNTVIZmhQTmEyL29wb3RQeUY2WTVielRBTUJnTlYKSFJNRUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDUm82RnVjQSt5c1ZaY3hPdTRHQnlKdGpULwpPeWt6L3V2Y0piSTgyaTV3R09uby9HZ1NUYXRCVDZCWXlLeFdoR3ZHV3Z2ZkgwSVB1OU9CWUgvUE1oYVU0MDZ4CjBWanIxc20xQlV3NFFPRmJpczFzZTJjMUQvbGhYcWw3RzhWMGhvRHE1YzhOWUI4cVhTR21pMEx4Zlkvd2Q5TU8KSHN1L3VUeHMwSEFLN1lhcGVDalpzc2FyTk5DdmpwaHdsWTRDdVEzVTBnYmdoeGhVZzlQYy9GT1ZqT1Z4R0REUwpWSHhyTnZ5dmJXaEtLWEl5bk5JdTRLSTVnNGJ2Um9yaEJuZ0xQTDZldDhibit1eDFnekl5aXd5S2QzNEFHQjBFCjRRbEw3emxqOTh1b1hJYS9MelRRbVQ4MGwvMHNxOERoL0s2SXZiYnlkYXc1TktTRU5aL2xWd0ZMYVdqcAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
